name = "hex-poly-z"
defaultTargets = ["HexPolyZ"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPoly"
git = "https://github.com/leanprover/hex-poly.git"
rev = "v0.3.0"

[[require]]
name = "HexArith"
git = "https://github.com/leanprover/hex-arith.git"
rev = "v0.3.0"

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "v0.3.0"

[[require]]
name = "HexModArith"
git = "https://github.com/leanprover/hex-mod-arith.git"
rev = "v0.3.0"

[[lean_lib]]
name = "HexPolyZ"
