name = "hex-poly-z"
defaultTargets = ["HexPolyZ"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPoly"
git = "https://github.com/leanprover/hex-poly.git"
rev = "069aaf4c0ebd966306f3254d7a180586f9ab893f"

[[require]]
name = "HexArith"
git = "https://github.com/leanprover/hex-arith.git"
rev = "e96af967c9dbdf95937d845e9448e05c04e9e975"

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "a3ab4fd9a79efbe6b07337836b3b5828d22d65a6"

[[lean_lib]]
name = "HexPolyZ"
